import { Geist } from 'next/font/google'
import NavBar from '../components/NavBar'
import Bottom from '@/components/Bottom'
import './globals.css'
import { Lato } from 'next/font/google'
import PopupProvider from '@/components/PopUpProvider'
import ContactModal from '@/components/ContactModal'

const lato = Lato({
    variable: '--font-lato',
    subsets: ['latin'],
    weight: ['100', '300', '400', '700', '900'],
})

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${lato.variable} antialiased`}
            >
                <PopupProvider>
                    <NavBar />
                    {children}
                    <Bottom />
                    <ContactModal />
                </PopupProvider>
            </body>
        </html>
    )
}
